### ISSUE TITLE
cal_jacobian for SingleArm

### ISSUE THREAD

**Issue by Chu4nQ1n** [jdj2261/pykin#12]
Hi jdj2261,

Thanks for developing this awesome library. I am trying to cal_jacobian for my customised SingleArm. According to your example, _pekin/examples/robot_jacobian.py_, it uses _robot.arm_type_ for BimanualArm. But how should I cal_jacobian for SingleArm? where SingleArm object has no attribute 'arm_type'

Thanks for your help.
Chuan

**Comment by jdj2261** [comment]
Hello Chuan,
Thank you for your interest in our library.

In case of a single arm, you can use the code below.

-----------------------------------------------------------------
import numpy as np
from pykin.kinematics.transform import Transform
from pykin.robots.single_arm import SingleArm
from pykin.kinematics import jacobian as jac

file_path = "urdf/doosan/doosan_with_robotiq140.urdf"
robot = SingleArm(
    file_path,
    Transform(rot=[0.0, 0.0, 0.0], pos=[0, 0, 0]),
    has_gripper=True,
    gripper_name="robotiq140",
)
robot.setup_link_name("base_0", "right_hand")
thetas = np.zeros(6)
fk = robot.forward_kin(thetas)

J = jac.calc_jacobian(robot.desired_frames, fk, len(np.zeros(7)))

-----------------------------------------------------------------

Thank you
