### ISSUE TITLE
Path planning removed

### ISSUE THREAD

**Issue by FioreApi03** [jdj2261/pykin#4]
Hi,
I find that the path planning of previous versions of the library was so useful.
In this last version it was removed. It's possible restore it?

**Comment by jdj2261** [comment]
Hi, first of all, thank you for your interest in my code.
pykin is a library that solves the kinematics of a robot, and we wanted to treat it differently from planning. 
We wanted to prevent code verbosity by creating a pytamp library as a planning-related library.
If you are curious about planning, you can refer to the pytamp library ([here](https://github.com/jdj2261/pytamp)).
Thank you.
