### ISSUE TITLE
pip install doesn't have a example folder

### ISSUE THREAD

**Issue by benthebear93** [jdj2261/pykin#5]
Readme guide user to install pykin with pip3.

However, when i check ~/.local/lib/python3.8/site-packages/pykin directory, there was no example folder. 

```
benlee@benlee:~/.local/lib/python3.8/site-packages/pykin$ ls
asset  collision  geometry  __init__.py  kinematics  models  __pycache__  robots  utils  _version.py
```

either your pip install is broken or i am missing something!
It would be much better Readme if it guide to install with git clone or tell people where the package will be installed ;)

best regard :)

**Comment by jdj2261** [comment]
Thank you! benthebear93. 

Thanks to you, I'm trying to manage this library again. 
Thank you for using it and for your interest.

 If you have any corrections or additions in the future, please feel free to comment.
 
 Happy new year! :)
