### ISSUE TITLE
Error in running all files

### ISSUE THREAD

**Issue by vm533** [jdj2261/pykin#7]
Thanks for this amazing library. Whenever I try to run any of the files in Pykin library. I get below error. 

![image](https://github.com/jdj2261/pykin/assets/116013391/19a3fccf-f62a-470c-8393-da48c3326554)

Can you please help me in resolving this error.

**Comment by jdj2261** [comment]
Hello,

pykin has been tested on python3.9. It appears that some of the code in the standard library has been modified as the python version has changed.

Could you please try solving it by inserting the code below?
```python
try:
    from collections.abc import Iterable
except ImportError:
    from collections import Iterable
```
If it still doesn't work, please tell me again.

Thank you!

**Comment by vm533** [comment]
Hello... 
Still I get the same problem. Can you please provide me if  there is any alternative. I am using Python 3.10 version
